### ISSUE TITLE
Unable to build because of implicit memmem build error

### ISSUE THREAD

**Issue by coudrant** [openbmc/libpldm#12]
We are seeing the following build error though _GNU_SOURCE is defined.  We don't know how to correct or workaround this.
This is seen on main.

_../src/msgbuf.h:1155:31: error: implicit declaration of function ‘memmem’; did you mean ‘memset’? [-Werror=implicit-function-declaration]
 1155 |                 end = (char *)memmem(end, ctx->remaining - measured, &term,_

googletest| C++ compiler for the host machine: ccache c++ (gcc 11.4.0 "c++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
googletest| C++ linker for the host machine: c++ ld.bfd 2.38

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy

**Comment by amboar** [comment]
I'll take a look at this. Thanks for the report.
