### ISSUE TITLE
Non-portable boolean logic?

### ISSUE THREAD

**Issue by dcrowell77** [openbmc/libpldm#13]
In the process of pulling in a newer version of this repo we ran into an issue with this new code in platform.c.

	if (SIZE_MAX - (sizeof(*effecter) - sizeof(effecter->possible_states) <
			possible_states_size)) {
		return PLDM_ERROR;
	}

I don't really understand what that logic is attempting to check.  It seems like there is an inherent assumption that SIZE_MAX is equivalent to a "true" result from the comparison, but that isn't part of any standard I'm aware of.  What am I missing?  I did a random experiment using baseline gcc on a RHEL8 x86 box and every expression I put inside there leads to a true evaluation of the if.

**Comment by williamspatrick** [comment]
SIZE_MAX should be the maximum representable integer by `size_t`.  It should come from `stdint.h`.

I think this is ensuring that the bit structure can fit in a size_t, right?

**Comment by dcrowell77** [comment]
No, the code is comparing SIZE_MAX against the result of the comparison.  After looking further, we are starting to think this is just a typo with the parentheses since it looks different in other code nearby.

Compare to this, notice the second paren after possible_states...
```
	if (SIZE_MAX - (sizeof(*sensor) - sizeof(sensor->possible_states)) <
	    possible_states_size) {
		return PLDM_ERROR;
	}
```

**Comment by amboar** [comment]
@dcrowell77 can you please provide the compiler error you see? The more specifics we have the better.

However, the code you've pasted does contain a bug. Looking at `src/dsp/platform.c`, I suspect you're referring to this:

https://github.com/openbmc/libpldm/blob/main/src/dsp/platform.c#L31-L34

Hopefully the compiler error you paste in reply matches.

The intent is to check for arithmetic overflow involving the identified types.

I expect this diff should sort it out:

```diff
diff --git a/src/dsp/platform.c b/src/dsp/platform.c
index df7ea4a39197..8b6032c777bc 100644
--- a/src/dsp/platform.c
+++ b/src/dsp/platform.c
@@ -28,8 +28,8 @@ int encode_state_effecter_pdr(
                return PLDM_ERROR;
        }
 
-       if (SIZE_MAX - (sizeof(*effecter) - sizeof(effecter->possible_states) <
-                       possible_states_size)) {
+       if (SIZE_MAX - (sizeof(*effecter) - sizeof(effecter->possible_states)) <
+                       possible_states_size) {
                return PLDM_ERROR;
        }
 
```

**Comment by amboar** [comment]
(I suspect I got tripped by clangd auto-parenthesising the code and the closing paren ended up in the wrong spot)

**Comment by amboar** [comment]
Looks like that might be the only instance?

```shell
0 andrew@heihei:~/src/openbmc.org/openbmc/libpldm/origin (main) $ git grep -E -- '- \(.*\) <'
src/dsp/bios_table.c:   if (entry_length - (sizeof(*table_entry) - 1 + sizeof(str_length)) <
src/dsp/fru.c:  if (SIZE_MAX - (*curr_size + record_hdr_size) < tlvs_size) {
src/dsp/fru.c:  if (total_size - (*curr_size + record_hdr_size) < tlvs_size) {
src/dsp/platform.c:     if (SIZE_MAX - (sizeof(*effecter) - sizeof(effecter->possible_states) <
src/dsp/platform.c:     if (SIZE_MAX - (sizeof(*sensor) - sizeof(sensor->possible_states)) <
```

**Comment by amboar** [comment]
https://gerrit.openbmc.org/c/openbmc/libpldm/+/75704

**Comment by amboar** [comment]
Okay, when I wrote the comment I was expecting it to be one of the tautological-compare issues (I was after an error to confirm the line numbers involved).

Can you provide some feedback on the patch linked above? If not I'll merge it with the expectation that it resolves the problem.

**Comment by dcrowell77** [comment]
We made the same change locally and we were able to get past the immediate failure we were seeing.  I can't say everything is working as we're in the process of updating our subtree (which is many versions behind the current).

**Comment by amboar** [comment]
> We made the same change locally and we were able to get past the immediate failure we were seeing.

Great!

> I can't say everything is working as we're in the process of updating our subtree (which is many versions behind the current).

So if you're not doing so already, the intent is that to upgrade, you move between successive tags. New APIs are available at tag `N` before they are removed in tag `N+1`. Also, for the bulk-renames, `./scripts/apply-renames` and the configurations under the appropriate tag in the `evolutions/` directory will automatically update your sources to new API names.

As for implementation bugs like this one, hopefully there aren't too many from new changes :sweat_smile:
