### ISSUE TITLE
Avoid use of assert() in libpldm

### ISSUE THREAD

**Issue by arun-pm** [openbmc/libpldm#7]
In some of the APIs libpldm uses assert() for input validation. Which are destructive in nature and can cause whole application to exit on failure.
Eg:- https://github.com/openbmc/libpldm/blob/6c9c9172f60935936de8a79931718ff9766fe036/src/pdr.c#L934

Some issue scenarios :-
1. A single pldm daemon may support multiple PLDM types(PLDM FWUP, PLDM platform M&C etc..). In that case an error in one PLDM type should not assert() and cause entire application to exit. Eg:- An assert() in PLDM M&C can cause PLDM FWUP to fail due to application exit.
2. If a PLDM requester is using libpldm, then a malicious PLDM responder(eg: Add-in-card) can provide incorrect data and cause PLDM requester to assert() and exit the application. Which can further affect monitoring of other pldm devices and other pldm type functionality.

**Comment by amboar** [comment]
`assert()` is fine so long as it's followed by an early exit for the inverse condition. If there's no early exit following the assert then *that* is the bug.

Production builds should be compiled with `-DNDEBUG` to remove the asserts and avoid aborts.

So this is fine:

```
...
assert(foo)
if (!foo) {
    return -EINVAL;
}
...
// More processing having verified `!foo` is false
```

while this is not:

```
...
assert(foo)
...
// More processing that just assumes `!foo` is `false`.
...
```

**Comment by amboar** [comment]
From `man 3 assert`:

>       If the macro NDEBUG is defined at the moment <assert.h> was last
>       included, the macro assert() generates no code, and hence does
>       nothing at all.  It is not recommended to define NDEBUG if using
>       assert() to detect error conditions since the software may behave
>       non-deterministically.

https://www.man7.org/linux/man-pages/man3/assert.3.html

**Comment by arun-pm** [comment]
Agree. In this case if we use https://github.com/openbmc/libpldm/blob/6c9c9172f60935936de8a79931718ff9766fe036/src/pdr.c#L929 to parse a PDR data which is given by an add in card then it will result in case 2 as you explained. I believe that is an issue.

**Comment by amboar** [comment]
Fixed with all the changes leading up to https://github.com/openbmc/libpldm/commit/5cf32ea871f4472bd90440bea6ed266d96c6f73c
